---
- hosts: all
  connection: local
  become: true
     
  tasks:
    - name: ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: ansible
        minute: "*/30"
        job: ansible-pull -o -U https://github.com/alencar-felipe/ansible
       
- hosts: all
  become: true
  roles:
    - base
