---
- hosts: all
  connection: local
  become: true
     
  tasks:
    - name: add ansible user
      user:
        name: ansible
        system: yes

    - name: set up sudo for ansible user
      copy: 
        src: files/sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: ansible
        minute: "*/30"
        job: ansible-pull -o -U https://github.com/alencar-felipe/ansible
       
- hosts: all
  become: true
  roles:
    - base
