- name: include roles/desktop/tasks/packages.yml
  include: packages.yml

- name: include roles/workstation/tasks/gdm.yml
  include: gdm.yml

- name: include roles/workstation/tasks/gnome.yml
  include: gnome.yml

- name: include roles/workstation/tasks/fonts.yml
  include: fonts.yml

- name: include roles/workstation/tasks/wallpaper.yml
  include: wallpaper.yml
  
- name: include roles/workstation/tasks/nautilus.yml
  include: nautilus.yml

- name: include roles/workstation/tasks/alacritty.yml
  include: alacritty.yml

- name: include roles/workstation/tasks/chromium.yml
  include: chromium.yml

dependencies:
  - role: base
