- name: Copy daemon.json file (docker)
  copy:
    src: ../files/daemon.json
    dest: /etc/docker/daemon.json

- name: Creates docker data directory
  file:
    path: /data/docker-data
    recurse: yes
    state: directory