version: "3.3"

services:
  mongo:
    container_name: mongo
    image: mongo:4.0
    ports:
      - 27017:27017
    
    volumes:
      - /mnt/shared/mongodb:/data/db

    networks:
      default:
        aliases:
          - mongo

    restart: unless-stopped
    
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081

    networks:
      default:
        aliases:
          - mongo-express

    restart: unless-stopped

#  rclone:
#    container_name: rclone
#    build: ./images/rclone/
#    volumes:
#      - ./volumes/rclone:/config/rclone
#      - /mnt/shared:/data
#
#    networks:
#      default:
#        aliases:
#          - rclone
#
#    restart: unless-stopped

  minecraft:
    contaioner_name: minecraft
    image: itzg/minecraft-bedrock-server  
    ports:
      19132:19132/udp
      
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      ALLOW_CHEATS: "TRUE"
      DEFAULT_PLAYER_PERMISSION_LEVEL: visitor
      OPS: "2535429530304678"

    networks:
      default:
        aliases:
          - minecraft

    restart: unless-stoped

networks:
  default:
