- name: creates chromium extensions directory
  file:
    path: /etc/chromium/policies/managed/
    state: directory
    
- name: chromium extensions
  copy: 
    src: ../files/extensions.json
    dest: /etc/chromium/policies/managed/extensions.json
    owner: root
    group: root
    mode: 0444

- name: copy felipe_personal chromium preferences files
  copy: 
    src: ../files/default.json
    dest: /home/felipe/.config/chromium/felipe_personal.json
    owner: felipe
    group: felipe
    mode: 0444

- name: copy felipe_ufc chromium preferences files
  copy: 
    src: ../files/default.json
    dest: /home/felipe/.config/chromium/felipe_ufc.json
    owner: felipe
    group: felipe
    mode: 0444

- name: create chromium profiles
  shell: |
    cd $HOME/.config/chromium

    timeout 10 chromium --profile-directory="felipe_personal"
    timeout 10 chromium --profile-directory="felipe_ufc"

    jq -s '.[0] * .[1]' felipe_personal/Preferences \
    felipe_personal.json | sponge felipe_personal/Preferences
    
    jq -s '.[0] * .[1]' felipe_ufc/Preferences \
    felipe_ufc.json | sponge felipe_ufc/Preferences

  become: true
  become_user: felipe

