- name: creates chromium extensions directory
  file:
    path: /etc/chromium/policies/managed/
    state: directory
    
- name: chromium extensions
  copy: 
    src: ../files/extensions.json
    dest: /etc/chromium/policies/managed/extensions.json
    owner: root
    group: root
    mode: 0440
