- name: wallpaper cron job
  cron:
    name: wallpaper
    user: ansible
    special_time: reboot
    job: ln -sf "$(shuf -n1 -e /usr/share/wallpapers/*)" /usr/share/wallpapers/.wallpaper
    
- name: disable sshd on boot 
  cron:
    name: sshd disable
    user: ansible
    special_time: reboot
    job: sudo systemctl disable sshd && sudo systemctl stop sshd
