- name: Copy wallpaper file
  copy:
    src: files/wallpapers/
    dest: /home/file/wallpapers/
    owner: felipe group=felipe mode=600

- name: Set GNOME Wallpaper
  become_user: felipe
  dconf:
    key: "/org/gnome/desktop/background/picture-uri" 
    value: "'file:///home/felipe/wallpapers/1.jpg'"
