- name: Set GNOME Wallpaper
  become_user: felipe
  dconf:
    key: "/org/gnome/desktop/background/picture-uri" 
    value: "'file:///home/felipe/.wallpaper'"
    
- name: Set GTK theme
  become_user: felipe
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Pop-dark'"
    
- name: Set GTK icon theme
  become_user: felipe
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Pop'"

- name: Set gnome favorite apps
  become_user: felipe
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['chromium.desktop', 'org.gnome.Nautilus.desktop', 'Alacritty.desktop', 'VSCodium.desktop']"
