- name: Set keyboard layout
  become_user: felipe
  dconf:
    key: "/org/gnome/desktop/input-sources/sources" 
    value: "[('xkb', 'br')]"
    
- name: Set GNOME Wallpaper
  become_user: felipe
  dconf:
    key: "/org/gnome/desktop/background/picture-uri" 
    value: "'file:///usr/share/wallpapers/.wallpaper'"
    
- name: Set GTK theme
  become_user: felipe
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Pop-dark'"
    
- name: Set GTK icon theme
  become_user: felipe
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Pop'"

- name: Set gnome favorite apps
  become_user: felipe
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['chromium.desktop', 'org.gnome.Nautilus.desktop', 'Alacritty.desktop', 'VSCodium.desktop']"

- name: Set default apps
  copy: 
    src: ../files/mimeapps.list
    dest: /home/felipe/.config/mimeapps.list
    owner: felipe
    group: felipe
    mode: 0444
    
- name: Disable lock screen notifications
  become_user: felipe
  dconf:
    key: "/org/gnome/desktop/notifications/show-in-lock-screen"
    value: "false"
    
