tasks: 
- name: include roles/workstation/tasks/packages.yml
  import_tasks: packages.yml

- name: include roles/workstation/tasks/cron.yml
  import_tasks: cron.yml
 
- name: include roles/workstation/tasks/services.yml
  import_tasks: services.yml
  
- name: include roles/workstation/tasks/vscodium.yml
  import_tasks: vscodium.yml
  
- name: include roles/workstation/tasks/arduino.yml
  import_tasks: arduino.yml