- name: include roles/workstation/tasks/packages.yml
  include: packages.yml

- name: include roles/workstation/tasks/cron.yml
  include: cron.yml
 
- name: include roles/workstation/tasks/services.yml
  include: services.yml
  
- name: include roles/workstation/tasks/vscodium.yml
  include: vscodium.yml
  
- name: include roles/workstation/tasks/arduino.yml
  include: arduino.yml

- dependencies:
  - role: desktop
  - role: printing
  - role: modeling