- name: install workstation packages
  package: 
    name:
      - gdm
      - gnome-shell
      - gnome-control-center
      - gnome-tweaks
      - gnome-shell-extensions 
      - chrome-gnome-shell 
      - gnome-system-monitor 
      - networkmanager
      - gvfs-smb 
      - cups
      - fish
      - xterm
      - alacritty
      - nautilus
      - evince
      - chromium
      - vlc
      - libreoffice
      - inkscape
      - gimp
      - gparted
      - transmission-gtk
      - gedit
      - kdenlive
      - audacity
      - eog
      - torbrowser-launcher
      - arduino
      - obs-studio
      - gnome-calculator
      - simple-scan
      - powerline
      - python-psutil
      
- name: install workstation aur packages
  aur:
    name:
     - scrcpy
     - teamviewer-latest
     - debtap
     - vscodium-bin
     - pop-gtk-theme
     - pop-icon-theme
     
    user: ansible
    
