- name: install workstation packages
  package: 
    name:
      - inkscape
      - gimp
      - gparted
      - transmission-gtk
      - kdenlive
      - audacity
      - torbrowser-launcher
      - arduino
      - arduino-avr-core
      - obs-studio
      - powerline
      - virtualbox
      - jre-openjdk
      - jdk-openjdk
      - openjdk-doc
      - openjdk-src
      - java-openjfx
      - java-openjfx-doc
      - java-openjfx-src
      - keepassxc      
  
- name: install workstation aur packages
  aur:
    name:
     - scrcpy
     - teamviewer-latest
     - debtap
     - vscodium-bin
          
    user: ansible

#quick fix for arduino package installation
- name: arduino installation (quick fix)
  shell: |
    sudo pacman -Sy --noconfirm arduino
     
  become: true
  become_user: ansible
  
    
