- name: install workstation packages
  package: 
    name:
      - gdm
      - gnome-shell
      - gnome-control-center
      - gnome-tweaks
      - gnome-shell-extensions 
      - chrome-gnome-shell 
      - gnome-system-monitor 
      - networkmanager
      - gvfs-smb 
      - cups
      - alacritty
      - chromium
      - vlc
      - libreoffice
      - inkscape
      - gimp
      - gparted
      - code
      - transmission-gtk
      - gedit
      - kdenlive
      - audacity
      - eog
      - torbrowser-launcher
      - arduino
      - obs-studio
      - gnome-calculator
      - simple-scan
      
- name: install workstation aur packages
  aur:
    name: scrcpy
    user: ansible
    
