- name: Enable gdm service
  service:
    name: gdm
    enabled: yes

- name: Disable dhcpcd service
  service:
    name: dhcpcd
    enabled: no
    state: stopped

- name: Enable NetworkManager service
  service:
    name: NetworkManager
    enabled: yes
    state: started
    
- name: Enable cups service
  service:
    name: cups
    enabled: yes
    state: started 
