- name: vscodium extensions
  shell: |
    codium --install-extension coenraads.bracket-pair-colorizer-2
    codium --install-extension eamodio.gitlens
    codium --install-extension donjayamanne.githistory
    codium --install-extension wayou.vscode-todo-highlight
     
  become: true
  become_user: felipe
