# Window Customization
window:
  dimensions:
    columns: 80
    lines: 24
    
  padding:
    x: 10
    y: 10
    
  position:
    x: 30
    y: 30
    
  decorations: none
  
scrolling:
  history: 10000
  multiplier: 3
  
background_opacity: 0.90
window.dynamic_title: true

# Font Customization
font:
  normal:
    family: Fira Code
    style: Regular
    
  bold:
    family: Fira Code
    style: Bold
    
  italic:
    family: Fira Code
    style: Italic
    
  size: 10
  offset:
    x: 0
    y: 0
    
  glyph_offset:
    x: 0
    y: 0
    
  use_thin_strokes: false
  debug:
    persistent_logging: false
    
draw_bold_text_with_bright_colors: true

# GNOME Terminal Tango Dark
colors:
  primary:
    background: '0x2e3436'
    foreground: '0xd3d7cf'
    
  normal:
    black: '0x2e3436'
    red: '0xcc0000'
    green: '0x4e9a06'
    yellow: '0xc4a000'
    blue: '0x3465a4'
    magenta: '0x75507b'
    cyan: '0x06989a'
    white: '0xd3d7cf'

  bright:
    black: '0x555753'
    red: '0xef2929'
    green: '0x8ae234'
    yellow: '0xfce94f'
    blue: '0x729fcf'
    magenta: '0xad7fa8'
    cyan: '0x34e2e2'
    white: '0xeeeeec'

cursor:
  style: Block
  unfocused_hollow: true

mouse_bindings:
  - { mouse: Middle               , action: Paste                        }
  - { mouse: Right                , action: Copy                         }

key_bindings:
  - { key: Paste,                   action: Paste                        }
  - { key: Copy,                    action: Copy                         }

