# Window Customization
window:
  dimensions:
    columns: 80
    lines: 24
    
  padding:
    x: 25
    y: 25
    
  decorations: none
  
scrolling:
  history: 10000
  multiplier: 3
  
background_opacity: .8
window.dynamic_title: true

# Font Customization
font:
  normal:
    family: Fira Code
    style: Regular
    
  bold:
    family: Fira Code
    style: Bold
    
  italic:
    family: Fira Code
    style: Italic
    
  size: 10
  offset:
    x: 0
    y: 0
    
  glyph_offset:
    x: 0
    y: 0
    
  use_thin_strokes: false
  debug:
    persistent_logging: false
    
draw_bold_text_with_bright_colors: true

# https://github.com/eendroroy/alacritty-theme
# KDE Breeze (Ported from Konsole)
colors:
  # Default colors
  primary:
    background: '0x232627'
    foreground: '0xfcfcfc'

    dim_foreground: '0xeff0f1'
    bright_foreground: '0xffffff'
    dim_background: '0x31363b'
    bright_background: '0x000000'

  # Normal colors
  normal:
    black: '0x232627'
    red: '0xed1515'
    green: '0x11d116'
    yellow: '0xf67400'
    blue: '0x1d99f3'
    magenta: '0x9b59b6'
    cyan: '0x1abc9c'
    white: '0xfcfcfc'

  # Bright colors
  bright:
    black: '0x7f8c8d'
    red: '0xc0392b'
    green: '0x1cdc9a'
    yellow: '0xfdbc4b'
    blue: '0x3daee9'
    magenta: '0x8e44ad'
    cyan: '0x16a085'
    white: '0xffffff'

  # Dim colors
  dim:
    black: '0x31363b'
    red: '0x783228'
    green: '0x17a262'
    yellow: '0xb65619'
    blue: '0x1b668f'
    magenta: '0x614a73'
    cyan: '0x186c60'
    white: '0x63686d'

cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  - { key: N, mods: Control, action: SpawnNewInstance }

