- name: copy bashrc
  copy: 
    src: ../files/bashrc
    dest: /home/felipe/.bashrc
    owner: felipe

- name: git bash completion
  file:
    src: "/usr/share/bash-completion/completions/git"
    dest: "/etc/bash_completion.d/git"
    state: link

