- name: Ensure the locale en_US.UTF-8 enexists
  locale_gen:
    name: en_US.UTF-8
    state: present
    
- name: Ensure the locale pt_BR.UTF-8 enexists
  locale_gen:
    name: pt_BR.UTF-8
    state: present
    
- name: Set default locale
  copy: 
    src: ../files/locale
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0440
    
- name: Set default keyboard
  copy: 
    src: ../files/keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0440
    
- name: Set timezone
  timezone:
    name: America/Fortaleza
