- name: Ensure the locale en_US.UTF-8 enexists
  locale_gen:
    name: en_US.UTF-8
    state: present
    
- name: Ensure the locale pt_BR.UTF-8 enexists
  locale_gen:
    name: pt_BR.UTF-8
    state: present
    
- name: set up sudo for user felipe
  copy: 
    src: ../files/locale.conf
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: 0440
