- name: include roles/base/tasks/locale.yml
  import_tasks: locale.yml

- name: include roles/base/tasks/apt.yml
  import_tasks: apt.yml

- name: include roles/base/tasks/packages.yml
  import_tasks: packages.yml
  
- name: include roles/base/tasks/docker.yml
  import_tasks: docker.yml
  
- name: include roles/base/tasks/users.yml
  import_tasks: users.yml
  
- name: include roles/base/tasks/cron.yml
  import_tasks: cron.yml
  
- name: include roles/base/tasks/services.yml
  import_tasks: services.yml
  
- name: include roles/base/tasks/bash.yml
  import_tasks: bash.yml
  
- name: include roles/base/tasks/ssh.yml
  import_tasks: ssh.yml

- name: include roles/base/tasks/git.yml
  import_tasks: git.yml
