- name: Enable Cronie service
  service:
    name: cron
    enabled: yes
    state: started
  
- name: Disable ssh service
  service:
    name: ssh
    enabled: no
    state: stopped
    
- name: Enable Docker service
  service:
    name: docker
    enabled: yes
    state: started
    
