- name: Enable Cronie service
  service:
    name: cronie
    enabled: yes
    state: started
  
- name: Enable Docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: Enable time sync service
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started
