- name: add user felipe
  user:
    name: felipe
    groups: 'sudo, docker, uucp'
    state: present
    update_password: on_create
    password: $6$/E9TdqBxeQI2k$pMCyMyA0QG8f4DVj/HNz7N/AhxzUra37AFxTJrWmdrMKRVxsq9kbx4oBzhgb2atN715CrrUBWI6/KgBg4s.Qs.
    
- name: recursive ownership of home directory for felipe
  become: true
  shell: chown -R felipe /home/felipe
