- name: add ansible user
  user:
    name: ansible
    groups: 'docker'
    state: present
    system: yes

- name: set up sudo for ansible user
  copy: 
    src: ../files/sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
    
- name: add user felipe
  user:
    name: felipe
    groups: 'docker, uucp'
    state: present
    update_password: on_create
    password: $6$/E9TdqBxeQI2k$pMCyMyA0QG8f4DVj/HNz7N/AhxzUra37AFxTJrWmdrMKRVxsq9kbx4oBzhgb2atN715CrrUBWI6/KgBg4s.Qs.
    
- name: set up sudo for user felipe
  copy: 
    src: ../files/sudoer_felipe
    dest: /etc/sudoers.d/felipe
    owner: root
    group: root
    mode: 0440
    
- name: recursive ownership of home directory for felipe
  shell: chown -R felipe /home/felipe
