- name: add ansible user
  user:
    name: ansible
    system: yes

- name: set up sudo for ansible user
  copy: 
    src: ../files/sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
    
- name: add user felipe
  user:
    name: felipe
    system: yes

- name: set up sudo for user felipe
  copy: 
    src: ../files/sudoer_felipe
    dest: /etc/sudoers.d/felipe
    owner: root
    group: root
    mode: 0440
